/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AAssertStatement extends PStatement
{
    private PExpression _expression_;
    private PCommaexp _commaexp_;

    public AAssertStatement()
    {
    }

    public AAssertStatement(
        PExpression _expression_,
        PCommaexp _commaexp_)
    {
        setExpression(_expression_);

        setCommaexp(_commaexp_);

    }
    public Object clone()
    {
        return new AAssertStatement(
            (PExpression) cloneNode(_expression_),
            (PCommaexp) cloneNode(_commaexp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssertStatement(this);
    }

    public PExpression getExpression()
    {
        return _expression_;
    }

    public void setExpression(PExpression node)
    {
        if(_expression_ != null)
        {
            _expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expression_ = node;
    }

    public PCommaexp getCommaexp()
    {
        return _commaexp_;
    }

    public void setCommaexp(PCommaexp node)
    {
        if(_commaexp_ != null)
        {
            _commaexp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _commaexp_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_expression_)
            + toString(_commaexp_);
    }

    void removeChild(Node child)
    {
        if(_expression_ == child)
        {
            _expression_ = null;
            return;
        }

        if(_commaexp_ == child)
        {
            _commaexp_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        if(_commaexp_ == oldChild)
        {
            setCommaexp((PCommaexp) newChild);
            return;
        }

    }
}
