/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AValExpression extends PExpression
{
    private PValue _value_;
    private final LinkedList _commaval_ = new TypedLinkedList(new Commaval_Cast());

    public AValExpression()
    {
    }

    public AValExpression(
        PValue _value_,
        List _commaval_)
    {
        setValue(_value_);

        {
            this._commaval_.clear();
            this._commaval_.addAll(_commaval_);
        }

    }
    public Object clone()
    {
        return new AValExpression(
            (PValue) cloneNode(_value_),
            cloneList(_commaval_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAValExpression(this);
    }

    public PValue getValue()
    {
        return _value_;
    }

    public void setValue(PValue node)
    {
        if(_value_ != null)
        {
            _value_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _value_ = node;
    }

    public LinkedList getCommaval()
    {
        return _commaval_;
    }

    public void setCommaval(List list)
    {
        _commaval_.clear();
        _commaval_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_value_)
            + toString(_commaval_);
    }

    void removeChild(Node child)
    {
        if(_value_ == child)
        {
            _value_ = null;
            return;
        }

        if(_commaval_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_value_ == oldChild)
        {
            setValue((PValue) newChild);
            return;
        }

        for(ListIterator i = _commaval_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class Commaval_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PCommaval node = (PCommaval) o;

            if((node.parent() != null) &&
                (node.parent() != AValExpression.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AValExpression.this))
            {
                node.parent(AValExpression.this);
            }

            return node;
        }
    }
}
