/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.parser;

import minipython.lexer.*;
import minipython.node.*;
import minipython.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_shift;
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(Lexer lexer)
    {
        this.lexer = lexer;

        if(actionTable == null)
        {
            try
            {
                DataInputStream s = new DataInputStream(
                    new BufferedInputStream(
                    Parser.class.getResourceAsStream("parser.dat")));

                // read actionTable
                int length = s.readInt();
                actionTable = new int[length][][];
                for(int i = 0; i < actionTable.length; i++)
                {
                    length = s.readInt();
                    actionTable[i] = new int[length][3];
                    for(int j = 0; j < actionTable[i].length; j++)
                    {
                        for(int k = 0; k < 3; k++)
                        {
                            actionTable[i][j][k] = s.readInt();
                        }
                    }
                }

                // read gotoTable
                length = s.readInt();
                gotoTable = new int[length][][];
                for(int i = 0; i < gotoTable.length; i++)
                {
                    length = s.readInt();
                    gotoTable[i] = new int[length][2];
                    for(int j = 0; j < gotoTable[i].length; j++)
                    {
                        for(int k = 0; k < 2; k++)
                        {
                            gotoTable[i][j][k] = s.readInt();
                        }
                    }
                }

                // read errorMessages
                length = s.readInt();
                errorMessages = new String[length];
                for(int i = 0; i < errorMessages.length; i++)
                {
                    length = s.readInt();
                    StringBuffer buffer = new StringBuffer();

                    for(int j = 0; j < length; j++)
                    {
                        buffer.append(s.readChar());
                    }
                    errorMessages[i] = buffer.toString();
                }

                // read errors
                length = s.readInt();
                errors = new int[length];
                for(int i = 0; i < errors.length; i++)
                {
                    errors[i] = s.readInt();
                }

                s.close();
            }
            catch(Exception e)
            {
                throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
            }
        }
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private void push(int numstate, ArrayList listNode) throws ParserException, LexerException, IOException
    {
	this.nodeList = listNode;

        if(!stack.hasNext())
        {
            stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int state()
    {
        State s = (State) stack.previous();
        stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return (ArrayList) ((State) stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        converter.index = -1;
        token.apply(converter);
        return converter.index;
    }

    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null);

        List ign = null;
        while(true)
        {
            while(index(lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new TypedLinkedList(NodeCast.instance);
                }

                ign.add(lexer.next());
            }

            if(ign != null)
            {
                ignoredTokens.setIn(lexer.peek(), ign);
                ign = null;
            }

            last_pos = lexer.peek().getPos();
            last_line = lexer.peek().getLine();
            last_token = lexer.peek();

            int index = index(lexer.peek());
            action[0] = actionTable[state()][0][1];
            action[1] = actionTable[state()][0][2];

            int low = 1;
            int high = actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    action[0] = actionTable[state()][middle][1];
                    action[1] = actionTable[state()][middle][2];
                    break;
                }
            }

            switch(action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(lexer.next());
                        push(action[1], list);
                        last_shift = action[1];
                    }
		    break;
                case REDUCE:
                    switch(action[1])
                    {

                    case 0:
		    {
			ArrayList list = new0();
			push(goTo(0), list);
		    }
		    break;


                    case 1:
		    {
			ArrayList list = new1();
			push(goTo(0), list);
		    }
		    break;


                    case 2:
		    {
			ArrayList list = new2();
			push(goTo(1), list);
		    }
		    break;


                    case 3:
		    {
			ArrayList list = new3();
			push(goTo(1), list);
		    }
		    break;


                    case 4:
		    {
			ArrayList list = new4();
			push(goTo(2), list);
		    }
		    break;


                    case 5:
		    {
			ArrayList list = new5();
			push(goTo(2), list);
		    }
		    break;


                    case 6:
		    {
			ArrayList list = new6();
			push(goTo(3), list);
		    }
		    break;


                    case 7:
		    {
			ArrayList list = new7();
			push(goTo(3), list);
		    }
		    break;


                    case 8:
		    {
			ArrayList list = new8();
			push(goTo(3), list);
		    }
		    break;


                    case 9:
		    {
			ArrayList list = new9();
			push(goTo(3), list);
		    }
		    break;


                    case 10:
		    {
			ArrayList list = new10();
			push(goTo(4), list);
		    }
		    break;


                    case 11:
		    {
			ArrayList list = new11();
			push(goTo(5), list);
		    }
		    break;


                    case 12:
		    {
			ArrayList list = new12();
			push(goTo(5), list);
		    }
		    break;


                    case 13:
		    {
			ArrayList list = new13();
			push(goTo(6), list);
		    }
		    break;


                    case 14:
		    {
			ArrayList list = new14();
			push(goTo(6), list);
		    }
		    break;


                    case 15:
		    {
			ArrayList list = new15();
			push(goTo(6), list);
		    }
		    break;


                    case 16:
		    {
			ArrayList list = new16();
			push(goTo(6), list);
		    }
		    break;


                    case 17:
		    {
			ArrayList list = new17();
			push(goTo(6), list);
		    }
		    break;


                    case 18:
		    {
			ArrayList list = new18();
			push(goTo(6), list);
		    }
		    break;


                    case 19:
		    {
			ArrayList list = new19();
			push(goTo(6), list);
		    }
		    break;


                    case 20:
		    {
			ArrayList list = new20();
			push(goTo(6), list);
		    }
		    break;


                    case 21:
		    {
			ArrayList list = new21();
			push(goTo(6), list);
		    }
		    break;


                    case 22:
		    {
			ArrayList list = new22();
			push(goTo(6), list);
		    }
		    break;


                    case 23:
		    {
			ArrayList list = new23();
			push(goTo(6), list);
		    }
		    break;


                    case 24:
		    {
			ArrayList list = new24();
			push(goTo(6), list);
		    }
		    break;


                    case 25:
		    {
			ArrayList list = new25();
			push(goTo(6), list);
		    }
		    break;


                    case 26:
		    {
			ArrayList list = new26();
			push(goTo(6), list);
		    }
		    break;


                    case 27:
		    {
			ArrayList list = new27();
			push(goTo(6), list);
		    }
		    break;


                    case 28:
		    {
			ArrayList list = new28();
			push(goTo(6), list);
		    }
		    break;


                    case 29:
		    {
			ArrayList list = new29();
			push(goTo(6), list);
		    }
		    break;


                    case 30:
		    {
			ArrayList list = new30();
			push(goTo(6), list);
		    }
		    break;


                    case 31:
		    {
			ArrayList list = new31();
			push(goTo(6), list);
		    }
		    break;


                    case 32:
		    {
			ArrayList list = new32();
			push(goTo(6), list);
		    }
		    break;


                    case 33:
		    {
			ArrayList list = new33();
			push(goTo(6), list);
		    }
		    break;


                    case 34:
		    {
			ArrayList list = new34();
			push(goTo(6), list);
		    }
		    break;


                    case 35:
		    {
			ArrayList list = new35();
			push(goTo(6), list);
		    }
		    break;


                    case 36:
		    {
			ArrayList list = new36();
			push(goTo(6), list);
		    }
		    break;


                    case 37:
		    {
			ArrayList list = new37();
			push(goTo(6), list);
		    }
		    break;


                    case 38:
		    {
			ArrayList list = new38();
			push(goTo(6), list);
		    }
		    break;


                    case 39:
		    {
			ArrayList list = new39();
			push(goTo(7), list);
		    }
		    break;


                    case 40:
		    {
			ArrayList list = new40();
			push(goTo(7), list);
		    }
		    break;


                    case 41:
		    {
			ArrayList list = new41();
			push(goTo(7), list);
		    }
		    break;


                    case 42:
		    {
			ArrayList list = new42();
			push(goTo(7), list);
		    }
		    break;


                    case 43:
		    {
			ArrayList list = new43();
			push(goTo(8), list);
		    }
		    break;


                    case 44:
		    {
			ArrayList list = new44();
			push(goTo(9), list);
		    }
		    break;


                    case 45:
		    {
			ArrayList list = new45();
			push(goTo(9), list);
		    }
		    break;


                    case 46:
		    {
			ArrayList list = new46();
			push(goTo(9), list);
		    }
		    break;


                    case 47:
		    {
			ArrayList list = new47();
			push(goTo(9), list);
		    }
		    break;


                    case 48:
		    {
			ArrayList list = new48();
			push(goTo(9), list);
		    }
		    break;


                    case 49:
		    {
			ArrayList list = new49();
			push(goTo(9), list);
		    }
		    break;


                    case 50:
		    {
			ArrayList list = new50();
			push(goTo(9), list);
		    }
		    break;


                    case 51:
		    {
			ArrayList list = new51();
			push(goTo(9), list);
		    }
		    break;


                    case 52:
		    {
			ArrayList list = new52();
			push(goTo(9), list);
		    }
		    break;


                    case 53:
		    {
			ArrayList list = new53();
			push(goTo(10), list);
		    }
		    break;


                    case 54:
		    {
			ArrayList list = new54();
			push(goTo(10), list);
		    }
		    break;


                    case 55:
		    {
			ArrayList list = new55();
			push(goTo(10), list);
		    }
		    break;


                    case 56:
		    {
			ArrayList list = new56();
			push(goTo(11), list);
		    }
		    break;


                    case 57:
		    {
			ArrayList list = new57();
			push(goTo(11), list);
		    }
		    break;


                    case 58:
		    {
			ArrayList list = new58();
			push(goTo(11), list);
		    }
		    break;


                    case 59:
		    {
			ArrayList list = new59();
			push(goTo(11), list);
		    }
		    break;


                    case 60:
		    {
			ArrayList list = new60();
			push(goTo(12), list);
		    }
		    break;


                    case 61:
		    {
			ArrayList list = new61();
			push(goTo(12), list);
		    }
		    break;


                    case 62:
		    {
			ArrayList list = new62();
			push(goTo(13), list);
		    }
		    break;


                    case 63:
		    {
			ArrayList list = new63();
			push(goTo(13), list);
		    }
		    break;


                    case 64:
		    {
			ArrayList list = new64();
			push(goTo(13), list);
		    }
		    break;


                    case 65:
		    {
			ArrayList list = new65();
			push(goTo(13), list);
		    }
		    break;


                    case 66:
		    {
			ArrayList list = new66();
			push(goTo(13), list);
		    }
		    break;


                    case 67:
		    {
			ArrayList list = new67();
			push(goTo(14), list);
		    }
		    break;


                    case 68:
		    {
			ArrayList list = new68();
			push(goTo(14), list);
		    }
		    break;


                    case 69:
		    {
			ArrayList list = new69();
			push(goTo(15), list);
		    }
		    break;


                    case 70:
		    {
			ArrayList list = new70();
			push(goTo(15), list);
		    }
		    break;


                    case 71:
		    {
			ArrayList list = new71();
			push(goTo(15), list);
		    }
		    break;


                    case 72:
		    {
			ArrayList list = new72();
			push(goTo(15), list);
		    }
		    break;


                    case 73:
		    {
			ArrayList list = new73();
			push(goTo(15), list);
		    }
		    break;


                    case 74:
		    {
			ArrayList list = new74();
			push(goTo(15), list);
		    }
		    break;


                    case 75:
		    {
			ArrayList list = new75();
			push(goTo(16), list);
		    }
		    break;


                    case 76:
		    {
			ArrayList list = new76();
			push(goTo(17), list);
		    }
		    break;


                    case 77:
		    {
			ArrayList list = new77();
			push(goTo(17), list);
		    }
		    break;


                    case 78:
		    {
			ArrayList list = new78();
			push(goTo(18), list);
		    }
		    break;


                    case 79:
		    {
			ArrayList list = new79();
			push(goTo(18), list);
		    }
		    break;


                    case 80:
		    {
			ArrayList list = new80();
			push(goTo(19), list);
		    }
		    break;


                    case 81:
		    {
			ArrayList list = new81();
			push(goTo(20), list);
		    }
		    break;


                    case 82:
		    {
			ArrayList list = new82();
			push(goTo(20), list);
		    }
		    break;


                    case 83:
		    {
			ArrayList list = new83();
			push(goTo(20), list);
		    }
		    break;


                    case 84:
		    {
			ArrayList list = new84();
			push(goTo(20), list);
		    }
		    break;


                    case 85:
		    {
			ArrayList list = new85();
			push(goTo(21), list);
		    }
		    break;


                    case 86:
		    {
			ArrayList list = new86();
			push(goTo(21), list);
		    }
		    break;


                    case 87:
		    {
			ArrayList list = new87();
			push(goTo(22), list);
		    }
		    break;


                    case 88:
		    {
			ArrayList list = new88();
			push(goTo(22), list);
		    }
		    break;


                    case 89:
		    {
			ArrayList list = new89();
			push(goTo(23), list);
		    }
		    break;


                    case 90:
		    {
			ArrayList list = new90();
			push(goTo(23), list);
		    }
		    break;


                    case 91:
		    {
			ArrayList list = new91();
			push(goTo(24), list);
		    }
		    break;


                    case 92:
		    {
			ArrayList list = new92();
			push(goTo(24), list);
		    }
		    break;


                    case 93:
		    {
			ArrayList list = new93();
			push(goTo(25), list);
		    }
		    break;


                    case 94:
		    {
			ArrayList list = new94();
			push(goTo(25), list);
		    }
		    break;

                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) lexer.next();
                        PGoal node1 = (PGoal) ((ArrayList)pop()).get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(last_token,
                        "[" + last_line + "," + last_pos + "] " +
                        errorMessages[errors[action[1]]]);
            }
        }
    }



    ArrayList new0()
    {
        ArrayList nodeList = new ArrayList();

        PGoal pgoalNode1;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        }

        pgoalNode1 = new AGoal(listNode2);
        }
	nodeList.add(pgoalNode1);
        return nodeList;
    }



    ArrayList new1()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PGoal pgoalNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pgoalNode1 = new AGoal(listNode3);
        }
	nodeList.add(pgoalNode1);
        return nodeList;
    }



    ArrayList new2()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommands pcommandsNode1;
        {
        PFunction pfunctionNode2;
        pfunctionNode2 = (PFunction)nodeArrayList1.get(0);

        pcommandsNode1 = new AFunctionCommands(pfunctionNode2);
        }
	nodeList.add(pcommandsNode1);
        return nodeList;
    }



    ArrayList new3()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommands pcommandsNode1;
        {
        PStatement pstatementNode2;
        pstatementNode2 = (PStatement)nodeArrayList1.get(0);

        pcommandsNode1 = new AStatementCommands(pstatementNode2);
        }
	nodeList.add(pcommandsNode1);
        return nodeList;
    }



    ArrayList new4()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunction pfunctionNode1;
        {
        TId tidNode2;
        Object nullNode3 = null;
        PStatement pstatementNode4;
        tidNode2 = (TId)nodeArrayList2.get(0);
        pstatementNode4 = (PStatement)nodeArrayList6.get(0);

        pfunctionNode1 = new ADefArgFunction(tidNode2, null, pstatementNode4);
        }
	nodeList.add(pfunctionNode1);
        return nodeList;
    }



    ArrayList new5()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunction pfunctionNode1;
        {
        TId tidNode2;
        PArgument pargumentNode3;
        PStatement pstatementNode4;
        tidNode2 = (TId)nodeArrayList2.get(0);
        pargumentNode3 = (PArgument)nodeArrayList4.get(0);
        pstatementNode4 = (PStatement)nodeArrayList7.get(0);

        pfunctionNode1 = new ADefArgFunction(tidNode2, pargumentNode3, pstatementNode4);
        }
	nodeList.add(pfunctionNode1);
        return nodeList;
    }



    ArrayList new6()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        TId tidNode2;
        Object nullNode3 = null;
        TypedLinkedList listNode4 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        {
        }

        pargumentNode1 = new AArgumentArgument(tidNode2, null, listNode4);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new7()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        TId tidNode2;
        PArg1 parg1Node3;
        TypedLinkedList listNode4 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        parg1Node3 = (PArg1)nodeArrayList2.get(0);
        {
        }

        pargumentNode1 = new AArgumentArgument(tidNode2, parg1Node3, listNode4);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new8()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        TId tidNode2;
        Object nullNode3 = null;
        TypedLinkedList listNode5 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        {
        TypedLinkedList listNode4 = new TypedLinkedList();
        listNode4 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pargumentNode1 = new AArgumentArgument(tidNode2, null, listNode5);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new9()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        TId tidNode2;
        PArg1 parg1Node3;
        TypedLinkedList listNode5 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        parg1Node3 = (PArg1)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode4 = new TypedLinkedList();
        listNode4 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pargumentNode1 = new AArgumentArgument(tidNode2, parg1Node3, listNode5);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new10()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArg1 parg1Node1;
        {
        PValue pvalueNode2;
        pvalueNode2 = (PValue)nodeArrayList2.get(0);

        parg1Node1 = new AArg1Arg1(pvalueNode2);
        }
	nodeList.add(parg1Node1);
        return nodeList;
    }



    ArrayList new11()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArg2 parg2Node1;
        {
        TId tidNode2;
        Object nullNode3 = null;
        tidNode2 = (TId)nodeArrayList2.get(0);

        parg2Node1 = new AArg2Arg2(tidNode2, null);
        }
	nodeList.add(parg2Node1);
        return nodeList;
    }



    ArrayList new12()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArg2 parg2Node1;
        {
        TId tidNode2;
        PArg1 parg1Node3;
        tidNode2 = (TId)nodeArrayList2.get(0);
        parg1Node3 = (PArg1)nodeArrayList3.get(0);

        parg2Node1 = new AArg2Arg2(tidNode2, parg1Node3);
        }
	nodeList.add(parg2Node1);
        return nodeList;
    }



    ArrayList new13()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList2.get(0);
        pstatementNode3 = (PStatement)nodeArrayList4.get(0);

        pstatementNode1 = new AIfStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new14()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList3.get(0);
        pstatementNode3 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AIfStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new15()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList2.get(0);
        pstatementNode3 = (PStatement)nodeArrayList4.get(0);

        pstatementNode1 = new AWhileStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new16()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList3.get(0);
        pstatementNode3 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AWhileStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new17()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        TId tidNode3;
        PStatement pstatementNode4;
        tidNode2 = (TId)nodeArrayList2.get(0);
        tidNode3 = (TId)nodeArrayList4.get(0);
        pstatementNode4 = (PStatement)nodeArrayList6.get(0);

        pstatementNode1 = new AForStatement(tidNode2, tidNode3, pstatementNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new18()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        TId tidNode3;
        PStatement pstatementNode4;
        tidNode2 = (TId)nodeArrayList3.get(0);
        tidNode3 = (TId)nodeArrayList5.get(0);
        pstatementNode4 = (PStatement)nodeArrayList7.get(0);

        pstatementNode1 = new AForStatement(tidNode2, tidNode3, pstatementNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new19()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pstatementNode1 = new AReturnStatement(pexpressionNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new20()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AReturnStatement(pexpressionNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new21()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new22()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        {
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new23()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new24()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new25()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AEqualStatement(tidNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new26()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);

        pstatementNode1 = new AEqualStatement(tidNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new27()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AMeqStatement(tidNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new28()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);

        pstatementNode1 = new AMeqStatement(tidNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new29()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new ADeqStatement(tidNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new30()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);

        pstatementNode1 = new ADeqStatement(tidNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new31()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode4;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList6.get(0);

        pstatementNode1 = new ABracketsStatement(tidNode2, pexpressionNode3, pexpressionNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new32()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode4;
        tidNode2 = (TId)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList7.get(0);

        pstatementNode1 = new ABracketsStatement(tidNode2, pexpressionNode3, pexpressionNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new33()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        Object nullNode3 = null;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pstatementNode1 = new AAssertStatement(pexpressionNode2, null);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new34()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        Object nullNode3 = null;
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AAssertStatement(pexpressionNode2, null);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new35()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        PCommaexp pcommaexpNode3;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        pcommaexpNode3 = (PCommaexp)nodeArrayList3.get(0);

        pstatementNode1 = new AAssertStatement(pexpressionNode2, pcommaexpNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new36()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        PCommaexp pcommaexpNode3;
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        pcommaexpNode3 = (PCommaexp)nodeArrayList4.get(0);

        pstatementNode1 = new AAssertStatement(pexpressionNode2, pcommaexpNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new37()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PFunctionCall pfunctioncallNode2;
        pfunctioncallNode2 = (PFunctionCall)nodeArrayList1.get(0);

        pstatementNode1 = new AFunctionCallStatement(pfunctioncallNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new38()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PFunctionCall pfunctioncallNode2;
        pfunctioncallNode2 = (PFunctionCall)nodeArrayList2.get(0);

        pstatementNode1 = new AFunctionCallStatement(pfunctioncallNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new39()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        pcomparisonNode1 = (PComparison)nodeArrayList1.get(0);
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new40()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PComparison pcomparisonNode2;
        pcomparisonNode2 = (PComparison)nodeArrayList2.get(0);

        pcomparisonNode1 = new ANotComparison(pcomparisonNode2);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new41()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PComparison pcomparisonNode2;
        PComparison pcomparisonNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList1.get(0);
        pcomparisonNode3 = (PComparison)nodeArrayList3.get(0);

        pcomparisonNode1 = new AAndComparison(pcomparisonNode2, pcomparisonNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new42()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PComparison pcomparisonNode2;
        PComparison pcomparisonNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList1.get(0);
        pcomparisonNode3 = (PComparison)nodeArrayList3.get(0);

        pcomparisonNode1 = new AOrComparison(pcomparisonNode2, pcomparisonNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new43()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        pcomparisonNode1 = (PComparison)nodeArrayList1.get(0);
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new44()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);

        pcomparisonNode1 = new AExpressionComparison(pexpressionNode2);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new45()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        TTrue ttrueNode2;
        ttrueNode2 = (TTrue)nodeArrayList1.get(0);

        pcomparisonNode1 = new ATrueComparison(ttrueNode2);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new46()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        TFalse tfalseNode2;
        tfalseNode2 = (TFalse)nodeArrayList1.get(0);

        pcomparisonNode1 = new AFalseComparison(tfalseNode2);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new47()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new ALesscComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new48()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new AGreatcComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new49()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new AGeqComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new50()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new ALeqComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new51()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new ANeqComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new52()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new AEqComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new53()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new54()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AAdditionExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new55()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new ASubtractionExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new56()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new57()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AMultExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new58()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new ADivExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new59()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new APerExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new60()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new61()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new APowerExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new62()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new63()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pexpressionNode1 = new APreAugExpression(pexpressionNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new64()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pexpressionNode1 = new APreDecExpression(pexpressionNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new65()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);

        pexpressionNode1 = new APostAugExpression(pexpressionNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new66()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);

        pexpressionNode1 = new APostDecExpression(pexpressionNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new67()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList1.get(0);

        pexpressionNode1 = new AIdentifierExpression(tidNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new68()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AIdExprExpression(tidNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new69()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PFunctionCall pfunctioncallNode2;
        pfunctioncallNode2 = (PFunctionCall)nodeArrayList1.get(0);

        pexpressionNode1 = new AFunctionCallExpression(pfunctioncallNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new70()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new71()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PValue pvalueNode2;
        pvalueNode2 = (PValue)nodeArrayList1.get(0);

        pexpressionNode1 = new AValueExpression(pvalueNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new72()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PValue pvalueNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pvalueNode2 = (PValue)nodeArrayList2.get(0);
        {
        }

        pexpressionNode1 = new AValExpression(pvalueNode2, listNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new73()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PValue pvalueNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pvalueNode2 = (PValue)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pexpressionNode1 = new AValExpression(pvalueNode2, listNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new74()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pexpressionNode1 = new AExprExpression(pexpressionNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new75()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommaval pcommavalNode1;
        {
        PValue pvalueNode2;
        pvalueNode2 = (PValue)nodeArrayList2.get(0);

        pcommavalNode1 = new ACommavalCommaval(pvalueNode2);
        }
	nodeList.add(pcommavalNode1);
        return nodeList;
    }



    ArrayList new76()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunctionCall pfunctioncallNode1;
        {
        TId tidNode2;
        Object nullNode3 = null;
        tidNode2 = (TId)nodeArrayList1.get(0);

        pfunctioncallNode1 = new AFunctionCallFunctionCall(tidNode2, null);
        }
	nodeList.add(pfunctioncallNode1);
        return nodeList;
    }



    ArrayList new77()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunctionCall pfunctioncallNode1;
        {
        TId tidNode2;
        PArglist parglistNode3;
        tidNode2 = (TId)nodeArrayList1.get(0);
        parglistNode3 = (PArglist)nodeArrayList3.get(0);

        pfunctioncallNode1 = new AFunctionCallFunctionCall(tidNode2, parglistNode3);
        }
	nodeList.add(pfunctioncallNode1);
        return nodeList;
    }



    ArrayList new78()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArglist parglistNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        }

        parglistNode1 = new AArglistArglist(pexpressionNode2, listNode3);
        }
	nodeList.add(parglistNode1);
        return nodeList;
    }



    ArrayList new79()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArglist parglistNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        parglistNode1 = new AArglistArglist(pexpressionNode2, listNode4);
        }
	nodeList.add(parglistNode1);
        return nodeList;
    }



    ArrayList new80()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommaexp pcommaexpNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pcommaexpNode1 = new ACommaexpCommaexp(pexpressionNode2);
        }
	nodeList.add(pcommaexpNode1);
        return nodeList;
    }



    ArrayList new81()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TId tidNode2;
        PFunctionCall pfunctioncallNode3;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pfunctioncallNode3 = (PFunctionCall)nodeArrayList3.get(0);

        pvalueNode1 = new AFunctionCallValue(tidNode2, pfunctioncallNode3);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new82()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TNumber tnumberNode2;
        tnumberNode2 = (TNumber)nodeArrayList1.get(0);

        pvalueNode1 = new ANumberValue(tnumberNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new83()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TString tstringNode2;
        tstringNode2 = (TString)nodeArrayList1.get(0);

        pvalueNode1 = new AStringValue(tstringNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new84()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TNone tnoneNode2;
        tnoneNode2 = (TNone)nodeArrayList1.get(0);

        pvalueNode1 = new ANoneValue(tnoneNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new85()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PCommands pcommandsNode1;
        pcommandsNode1 = (PCommands)nodeArrayList1.get(0);
	if(pcommandsNode1 != null)
	{
	  listNode2.add(pcommandsNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new86()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PCommands pcommandsNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pcommandsNode2 = (PCommands)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pcommandsNode2 != null)
	{
	  listNode3.add(pcommandsNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new87()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PArg2 parg2Node1;
        parg2Node1 = (PArg2)nodeArrayList1.get(0);
	if(parg2Node1 != null)
	{
	  listNode2.add(parg2Node1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new88()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PArg2 parg2Node2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        parg2Node2 = (PArg2)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(parg2Node2 != null)
	{
	  listNode3.add(parg2Node2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new89()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        TTab ttabNode1;
        ttabNode1 = (TTab)nodeArrayList1.get(0);
	if(ttabNode1 != null)
	{
	  listNode2.add(ttabNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new90()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        TTab ttabNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        ttabNode2 = (TTab)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(ttabNode2 != null)
	{
	  listNode3.add(ttabNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new91()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PCommaexp pcommaexpNode1;
        pcommaexpNode1 = (PCommaexp)nodeArrayList1.get(0);
	if(pcommaexpNode1 != null)
	{
	  listNode2.add(pcommaexpNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new92()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PCommaexp pcommaexpNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pcommaexpNode2 = (PCommaexp)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pcommaexpNode2 != null)
	{
	  listNode3.add(pcommaexpNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new93()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PCommaval pcommavalNode1;
        pcommavalNode1 = (PCommaval)nodeArrayList1.get(0);
	if(pcommavalNode1 != null)
	{
	  listNode2.add(pcommavalNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new94()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PCommaval pcommavalNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pcommavalNode2 = (PCommaval)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pcommavalNode2 != null)
	{
	  listNode3.add(pcommavalNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, REDUCE, 0}, {0, SHIFT, 1}, {6, SHIFT, 2}, {16, SHIFT, 3}, {27, SHIFT, 4}, {31, SHIFT, 5}, {32, SHIFT, 6}, {33, SHIFT, 7}, {34, SHIFT, 8}, {48, SHIFT, 9}, },
			{{-1, REDUCE, 89}, },
			{{-1, ERROR, 2}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 3}, {48, SHIFT, 33}, },
			{{-1, ERROR, 4}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {41, SHIFT, 34}, {43, SHIFT, 35}, {45, SHIFT, 36}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 5}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {41, SHIFT, 34}, {43, SHIFT, 35}, {45, SHIFT, 36}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 6}, {48, SHIFT, 42}, },
			{{-1, ERROR, 7}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 8}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 9}, {4, SHIFT, 45}, {5, SHIFT, 46}, {13, SHIFT, 47}, {18, SHIFT, 48}, {20, SHIFT, 49}, },
			{{-1, ERROR, 10}, {50, ACCEPT, -1}, },
			{{-1, REDUCE, 85}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 37}, },
			{{-1, REDUCE, 1}, {0, SHIFT, 1}, {6, SHIFT, 2}, {16, SHIFT, 3}, {27, SHIFT, 4}, {31, SHIFT, 5}, {32, SHIFT, 6}, {33, SHIFT, 7}, {34, SHIFT, 8}, {48, SHIFT, 9}, },
			{{-1, ERROR, 16}, {0, SHIFT, 51}, {6, SHIFT, 52}, {27, SHIFT, 53}, {31, SHIFT, 54}, {32, SHIFT, 55}, {33, SHIFT, 56}, {34, SHIFT, 57}, {48, SHIFT, 58}, },
			{{-1, REDUCE, 84}, },
			{{-1, ERROR, 18}, {48, SHIFT, 60}, },
			{{-1, ERROR, 19}, {48, SHIFT, 60}, },
			{{-1, ERROR, 20}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 21}, {1, SHIFT, 17}, {47, SHIFT, 22}, {48, SHIFT, 64}, {49, SHIFT, 24}, },
			{{-1, REDUCE, 82}, },
			{{-1, REDUCE, 67}, {18, SHIFT, 48}, {20, SHIFT, 66}, {24, SHIFT, 67}, },
			{{-1, REDUCE, 83}, },
			{{-1, REDUCE, 33}, {2, SHIFT, 68}, {3, SHIFT, 69}, {22, SHIFT, 70}, },
			{{-1, REDUCE, 53}, {9, SHIFT, 72}, {10, SHIFT, 73}, {12, SHIFT, 74}, },
			{{-1, REDUCE, 56}, {11, SHIFT, 75}, },
			{{-1, REDUCE, 60}, },
			{{-1, REDUCE, 70}, {7, SHIFT, 76}, {8, SHIFT, 77}, },
			{{-1, REDUCE, 62}, },
			{{-1, REDUCE, 69}, },
			{{-1, REDUCE, 71}, },
			{{-1, ERROR, 33}, {18, SHIFT, 78}, },
			{{-1, ERROR, 34}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {43, SHIFT, 35}, {45, SHIFT, 36}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, REDUCE, 45}, },
			{{-1, REDUCE, 46}, },
			{{-1, ERROR, 37}, {44, SHIFT, 81}, },
			{{-1, ERROR, 38}, {23, SHIFT, 82}, {42, SHIFT, 83}, },
			{{-1, REDUCE, 43}, {44, REDUCE, 39}, },
			{{-1, REDUCE, 44}, {2, SHIFT, 68}, {3, SHIFT, 69}, {35, SHIFT, 84}, {36, SHIFT, 85}, {37, SHIFT, 86}, {38, SHIFT, 87}, {39, SHIFT, 88}, {40, SHIFT, 89}, },
			{{-1, ERROR, 41}, {44, SHIFT, 90}, },
			{{-1, ERROR, 42}, {28, SHIFT, 91}, },
			{{-1, REDUCE, 21}, {2, SHIFT, 68}, {3, SHIFT, 69}, {22, SHIFT, 70}, },
			{{-1, REDUCE, 19}, {2, SHIFT, 68}, {3, SHIFT, 69}, },
			{{-1, ERROR, 45}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 46}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 47}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 48}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {19, SHIFT, 97}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 49}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, REDUCE, 86}, },
			{{-1, REDUCE, 90}, },
			{{-1, ERROR, 52}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 53}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {41, SHIFT, 34}, {43, SHIFT, 35}, {45, SHIFT, 36}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 54}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {41, SHIFT, 34}, {43, SHIFT, 35}, {45, SHIFT, 36}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 55}, {48, SHIFT, 104}, },
			{{-1, ERROR, 56}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 57}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 58}, {4, SHIFT, 107}, {5, SHIFT, 108}, {13, SHIFT, 109}, {18, SHIFT, 48}, {20, SHIFT, 110}, },
			{{-1, REDUCE, 38}, },
			{{-1, REDUCE, 67}, {20, SHIFT, 66}, },
			{{-1, REDUCE, 63}, },
			{{-1, REDUCE, 64}, },
			{{-1, ERROR, 63}, {2, SHIFT, 68}, {3, SHIFT, 69}, {19, SHIFT, 111}, },
			{{-1, ERROR, 64}, {24, SHIFT, 67}, },
			{{-1, ERROR, 65}, {21, SHIFT, 112}, {22, SHIFT, 113}, },
			{{-1, ERROR, 66}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 67}, {48, SHIFT, 117}, },
			{{-1, ERROR, 68}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 69}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 70}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, REDUCE, 35}, },
			{{-1, ERROR, 72}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 73}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 74}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 75}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, REDUCE, 65}, },
			{{-1, REDUCE, 66}, },
			{{-1, ERROR, 78}, {19, SHIFT, 126}, {48, SHIFT, 127}, },
			{{-1, REDUCE, 40}, },
			{{-1, REDUCE, 43}, },
			{{-1, ERROR, 81}, {0, SHIFT, 1}, {6, SHIFT, 2}, {27, SHIFT, 4}, {31, SHIFT, 5}, {32, SHIFT, 6}, {33, SHIFT, 7}, {34, SHIFT, 8}, {48, SHIFT, 9}, },
			{{-1, ERROR, 82}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {43, SHIFT, 35}, {45, SHIFT, 36}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 83}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {43, SHIFT, 35}, {45, SHIFT, 36}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 84}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 85}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 86}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 87}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 88}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 89}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 90}, {0, SHIFT, 1}, {6, SHIFT, 2}, {27, SHIFT, 4}, {31, SHIFT, 5}, {32, SHIFT, 6}, {33, SHIFT, 7}, {34, SHIFT, 8}, {48, SHIFT, 9}, },
			{{-1, ERROR, 91}, {48, SHIFT, 139}, },
			{{-1, REDUCE, 91}, },
			{{-1, REDUCE, 23}, {22, SHIFT, 70}, },
			{{-1, REDUCE, 27}, {2, SHIFT, 68}, {3, SHIFT, 69}, },
			{{-1, REDUCE, 29}, {2, SHIFT, 68}, {3, SHIFT, 69}, },
			{{-1, REDUCE, 25}, {2, SHIFT, 68}, {3, SHIFT, 69}, },
			{{-1, REDUCE, 76}, },
			{{-1, REDUCE, 78}, {2, SHIFT, 68}, {3, SHIFT, 69}, {22, SHIFT, 70}, },
			{{-1, ERROR, 99}, {19, SHIFT, 142}, },
			{{-1, ERROR, 100}, {2, SHIFT, 68}, {3, SHIFT, 69}, {21, SHIFT, 143}, },
			{{-1, REDUCE, 34}, {2, SHIFT, 68}, {3, SHIFT, 69}, {22, SHIFT, 70}, },
			{{-1, ERROR, 102}, {44, SHIFT, 145}, },
			{{-1, ERROR, 103}, {44, SHIFT, 146}, },
			{{-1, ERROR, 104}, {28, SHIFT, 147}, },
			{{-1, REDUCE, 22}, {2, SHIFT, 68}, {3, SHIFT, 69}, {22, SHIFT, 70}, },
			{{-1, REDUCE, 20}, {2, SHIFT, 68}, {3, SHIFT, 69}, },
			{{-1, ERROR, 107}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 108}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 109}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, ERROR, 110}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, REDUCE, 74}, },
			{{-1, REDUCE, 72}, },
			{{-1, ERROR, 113}, {1, SHIFT, 17}, {47, SHIFT, 22}, {48, SHIFT, 64}, {49, SHIFT, 24}, },
			{{-1, REDUCE, 93}, },
			{{-1, ERROR, 115}, {21, SHIFT, 154}, {22, SHIFT, 113}, },
			{{-1, ERROR, 116}, {2, SHIFT, 68}, {3, SHIFT, 69}, {21, SHIFT, 156}, },
			{{-1, ERROR, 117}, {18, SHIFT, 48}, },
			{{-1, REDUCE, 81}, },
			{{-1, REDUCE, 54}, {9, SHIFT, 72}, {10, SHIFT, 73}, {12, SHIFT, 74}, },
			{{-1, REDUCE, 55}, {9, SHIFT, 72}, {10, SHIFT, 73}, {12, SHIFT, 74}, },
			{{-1, REDUCE, 80}, {2, SHIFT, 68}, {3, SHIFT, 69}, },
			{{-1, REDUCE, 59}, {11, SHIFT, 75}, },
			{{-1, REDUCE, 57}, {11, SHIFT, 75}, },
			{{-1, REDUCE, 58}, {11, SHIFT, 75}, },
			{{-1, REDUCE, 61}, },
			{{-1, ERROR, 126}, {44, SHIFT, 157}, },
			{{-1, REDUCE, 6}, {13, SHIFT, 158}, {22, SHIFT, 159}, },
			{{-1, ERROR, 128}, {19, SHIFT, 163}, },
			{{-1, REDUCE, 13}, },
			{{-1, REDUCE, 41}, },
			{{-1, REDUCE, 42}, },
			{{-1, REDUCE, 47}, {2, SHIFT, 68}, {3, SHIFT, 69}, },
			{{-1, REDUCE, 48}, {2, SHIFT, 68}, {3, SHIFT, 69}, },
			{{-1, REDUCE, 49}, {2, SHIFT, 68}, {3, SHIFT, 69}, },
			{{-1, REDUCE, 50}, {2, SHIFT, 68}, {3, SHIFT, 69}, },
			{{-1, REDUCE, 51}, {2, SHIFT, 68}, {3, SHIFT, 69}, },
			{{-1, REDUCE, 52}, {2, SHIFT, 68}, {3, SHIFT, 69}, },
			{{-1, REDUCE, 15}, },
			{{-1, ERROR, 139}, {44, SHIFT, 164}, },
			{{-1, REDUCE, 92}, },
			{{-1, REDUCE, 79}, {22, SHIFT, 70}, },
			{{-1, REDUCE, 77}, },
			{{-1, ERROR, 143}, {13, SHIFT, 165}, },
			{{-1, REDUCE, 36}, },
			{{-1, ERROR, 145}, {0, SHIFT, 1}, {6, SHIFT, 2}, {27, SHIFT, 4}, {31, SHIFT, 5}, {32, SHIFT, 6}, {33, SHIFT, 7}, {34, SHIFT, 8}, {48, SHIFT, 9}, },
			{{-1, ERROR, 146}, {0, SHIFT, 1}, {6, SHIFT, 2}, {27, SHIFT, 4}, {31, SHIFT, 5}, {32, SHIFT, 6}, {33, SHIFT, 7}, {34, SHIFT, 8}, {48, SHIFT, 9}, },
			{{-1, ERROR, 147}, {48, SHIFT, 168}, },
			{{-1, REDUCE, 24}, {22, SHIFT, 70}, },
			{{-1, REDUCE, 28}, {2, SHIFT, 68}, {3, SHIFT, 69}, },
			{{-1, REDUCE, 30}, {2, SHIFT, 68}, {3, SHIFT, 69}, },
			{{-1, REDUCE, 26}, {2, SHIFT, 68}, {3, SHIFT, 69}, },
			{{-1, ERROR, 152}, {2, SHIFT, 68}, {3, SHIFT, 69}, {21, SHIFT, 169}, },
			{{-1, REDUCE, 75}, },
			{{-1, REDUCE, 73}, },
			{{-1, REDUCE, 94}, },
			{{-1, REDUCE, 68}, },
			{{-1, ERROR, 157}, {0, SHIFT, 1}, {6, SHIFT, 2}, {27, SHIFT, 4}, {31, SHIFT, 5}, {32, SHIFT, 6}, {33, SHIFT, 7}, {34, SHIFT, 8}, {48, SHIFT, 9}, },
			{{-1, ERROR, 158}, {1, SHIFT, 17}, {47, SHIFT, 22}, {48, SHIFT, 64}, {49, SHIFT, 24}, },
			{{-1, ERROR, 159}, {48, SHIFT, 172}, },
			{{-1, REDUCE, 7}, {22, SHIFT, 159}, },
			{{-1, REDUCE, 87}, },
			{{-1, REDUCE, 8}, {22, SHIFT, 159}, },
			{{-1, ERROR, 163}, {44, SHIFT, 175}, },
			{{-1, ERROR, 164}, {0, SHIFT, 1}, {6, SHIFT, 2}, {27, SHIFT, 4}, {31, SHIFT, 5}, {32, SHIFT, 6}, {33, SHIFT, 7}, {34, SHIFT, 8}, {48, SHIFT, 9}, },
			{{-1, ERROR, 165}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, REDUCE, 14}, },
			{{-1, REDUCE, 16}, },
			{{-1, ERROR, 168}, {44, SHIFT, 178}, },
			{{-1, ERROR, 169}, {13, SHIFT, 179}, },
			{{-1, REDUCE, 4}, },
			{{-1, REDUCE, 10}, },
			{{-1, REDUCE, 11}, {13, SHIFT, 158}, },
			{{-1, REDUCE, 9}, {22, SHIFT, 159}, },
			{{-1, REDUCE, 88}, },
			{{-1, ERROR, 175}, {0, SHIFT, 1}, {6, SHIFT, 2}, {27, SHIFT, 4}, {31, SHIFT, 5}, {32, SHIFT, 6}, {33, SHIFT, 7}, {34, SHIFT, 8}, {48, SHIFT, 9}, },
			{{-1, REDUCE, 17}, },
			{{-1, REDUCE, 31}, {2, SHIFT, 68}, {3, SHIFT, 69}, },
			{{-1, ERROR, 178}, {0, SHIFT, 1}, {6, SHIFT, 2}, {27, SHIFT, 4}, {31, SHIFT, 5}, {32, SHIFT, 6}, {33, SHIFT, 7}, {34, SHIFT, 8}, {48, SHIFT, 9}, },
			{{-1, ERROR, 179}, {1, SHIFT, 17}, {7, SHIFT, 18}, {8, SHIFT, 19}, {18, SHIFT, 20}, {20, SHIFT, 21}, {47, SHIFT, 22}, {48, SHIFT, 23}, {49, SHIFT, 24}, },
			{{-1, REDUCE, 12}, },
			{{-1, REDUCE, 5}, },
			{{-1, REDUCE, 18}, },
			{{-1, REDUCE, 32}, {2, SHIFT, 68}, {3, SHIFT, 69}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 10}, },
			{{-1, 11}, {15, 50}, },
			{{-1, 12}, },
			{{-1, 128}, },
			{{-1, 160}, {172, 180}, },
			{{-1, 161}, {162, 174}, {173, 174}, },
			{{-1, 13}, {81, 129}, {90, 138}, {145, 166}, {146, 167}, {157, 170}, {164, 176}, {175, 181}, {178, 182}, },
			{{-1, 37}, {5, 41}, {53, 102}, {54, 103}, },
			{{-1, 38}, {34, 79}, {82, 130}, {83, 131}, },
			{{-1, 39}, {34, 80}, {82, 80}, {83, 80}, },
			{{-1, 40}, {2, 25}, {7, 43}, {8, 44}, {20, 63}, {45, 94}, {46, 95}, {47, 96}, {48, 98}, {49, 100}, {52, 101}, {56, 105}, {57, 106}, {66, 116}, {70, 121}, {84, 132}, {85, 133}, {86, 134}, {87, 135}, {88, 136}, {89, 137}, {107, 149}, {108, 150}, {109, 151}, {110, 152}, {165, 177}, {179, 183}, },
			{{-1, 26}, {68, 119}, {69, 120}, },
			{{-1, 27}, {72, 122}, {73, 123}, {74, 124}, },
			{{-1, 28}, {75, 125}, },
			{{-1, 29}, {18, 61}, {19, 62}, },
			{{-1, 30}, },
			{{-1, 114}, {115, 155}, },
			{{-1, 31}, {0, 14}, {15, 14}, {16, 59}, {67, 118}, {81, 14}, {90, 14}, {145, 14}, {146, 14}, {157, 14}, {164, 14}, {175, 14}, {178, 14}, },
			{{-1, 99}, },
			{{-1, 92}, {25, 71}, {93, 140}, {101, 144}, {141, 140}, {148, 140}, },
			{{-1, 32}, {21, 65}, {113, 153}, {158, 171}, },
			{{-1, 15}, },
			{{-1, 162}, {160, 173}, },
			{{-1, 16}, },
			{{-1, 93}, {98, 141}, {105, 148}, },
			{{-1, 115}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: tab, 'assert', 'def', 'if', 'while', 'for', 'print', 'return', id, EOF",
			"expecting: tab, 'assert', 'if', 'while', 'for', 'print', 'return', id",
			"expecting: 'None', '++', '--', '(', '[', number, id, string",
			"expecting: id",
			"expecting: 'None', '++', '--', '(', '[', 'not', 'true', 'false', number, id, string",
			"expecting: '-=', '/=', '=', '(', '['",
			"expecting: EOF",
			"expecting: tab, '+', '-', 'assert', '%', '*', '**', '/', 'def', ')', ']', ',', 'and', 'if', 'while', 'for', 'print', 'return', '<', '>', '>=', '<=', '!=', '==', 'or', ':', id, EOF",
			"expecting: 'None', number, id, string",
			"expecting: tab, '+', '-', 'assert', '++', '--', '%', '*', '**', '/', 'def', '(', ')', '[', ']', ',', 'and', '.', 'if', 'while', 'for', 'print', 'return', '<', '>', '>=', '<=', '!=', '==', 'or', ':', id, EOF",
			"expecting: tab, '+', '-', 'assert', 'def', ',', 'if', 'while', 'for', 'print', 'return', id, EOF",
			"expecting: tab, '+', '-', 'assert', '%', '*', '/', 'def', ')', ']', ',', 'and', 'if', 'while', 'for', 'print', 'return', '<', '>', '>=', '<=', '!=', '==', 'or', ':', id, EOF",
			"expecting: tab, '+', '-', 'assert', '++', '--', '%', '*', '**', '/', 'def', ')', ']', ',', 'and', 'if', 'while', 'for', 'print', 'return', '<', '>', '>=', '<=', '!=', '==', 'or', ':', id, EOF",
			"expecting: '('",
			"expecting: 'None', '++', '--', '(', '[', 'true', 'false', number, id, string",
			"expecting: 'and', 'or', ':'",
			"expecting: ':'",
			"expecting: 'and', 'or'",
			"expecting: '+', '-', 'and', '<', '>', '>=', '<=', '!=', '==', 'or', ':'",
			"expecting: 'in'",
			"expecting: tab, '+', '-', 'assert', 'def', 'if', 'while', 'for', 'print', 'return', id, EOF",
			"expecting: 'None', '++', '--', '(', ')', '[', number, id, string",
			"expecting: tab, '+', '-', 'assert', '%', '*', '**', '/', 'def', ')', '[', ']', ',', 'and', 'if', 'while', 'for', 'print', 'return', '<', '>', '>=', '<=', '!=', '==', 'or', ':', id, EOF",
			"expecting: '+', '-', ')'",
			"expecting: '.'",
			"expecting: ']', ','",
			"expecting: ')', id",
			"expecting: tab, 'assert', 'def', ')', ',', 'if', 'while', 'for', 'print', 'return', id, EOF",
			"expecting: tab, 'assert', 'def', ',', 'if', 'while', 'for', 'print', 'return', id, EOF",
			"expecting: '+', '-', ')', ','",
			"expecting: ')'",
			"expecting: '+', '-', ']'",
			"expecting: tab, '+', '-', 'assert', 'def', ')', ',', 'if', 'while', 'for', 'print', 'return', id, EOF",
			"expecting: '=', ')', ','",
			"expecting: '+', '-', 'and', 'or', ':'",
			"expecting: ')', ','",
			"expecting: '='",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 4, 4, 3, 2, 2, 5, 6, 0, 0, 0, 0, 0, 1, 7, 3, 3, 2, 8, 7, 9, 7, 10, 11, 7, 7, 12, 7, 7, 7, 13, 14, 15, 15, 16, 17, 15, 18, 16, 19, 10, 20, 2, 2, 2, 21, 2, 0, 1, 2, 4, 4, 3, 2, 2, 5, 0, 22, 7, 7, 23, 24, 25, 2, 3, 2, 2, 2, 0, 2, 2, 2, 2, 7, 7, 26, 16, 16, 1, 14, 14, 2, 2, 2, 2, 2, 2, 1, 3, 27, 28, 20, 20, 20, 7, 29, 30, 31, 10, 16, 16, 19, 10, 20, 2, 2, 2, 2, 7, 7, 8, 25, 25, 31, 13, 7, 11, 11, 32, 7, 7, 7, 7, 16, 33, 30, 0, 16, 16, 34, 34, 34, 34, 34, 34, 0, 16, 27, 35, 7, 36, 0, 1, 1, 3, 28, 20, 20, 20, 31, 25, 7, 25, 12, 1, 8, 3, 35, 35, 35, 16, 1, 2, 0, 0, 16, 36, 0, 35, 33, 35, 35, 1, 0, 20, 1, 2, 35, 0, 0, 20, 
        };*/
}
