/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TPp extends Token
{
    public TPp()
    {
        super.setText("++");
    }

    public TPp(int line, int pos)
    {
        super.setText("++");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TPp(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPp(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TPp text.");
    }
}
